FROM python:3.13.1-bookworm

USER root
RUN apt update -y
RUN apt install -y pipx && \
    pipx install poetry==2.0.1
ENV HOME=/root
ENV PATH="$HOME/.local/bin:$PATH"

COPY run.sh /usr/local/src/run.sh
RUN chmod +x /usr/local/src/run.sh

CMD /usr/local/src/run.sh
