name: api
on:
  push:
    branches:
      - distribution
    paths:
      - chloria-backend/chloria-api/**
      - chloria-backend/Dockerfile.dist-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: metalwhaledev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:chloria-backend"
          file: Dockerfile.dist-api
          push: true
          tags: metalwhaledev/chloria-api:0.1.0
