name: migration
on:
  push:
    branches:
      - distribution
    paths:
      - chloria-backend/migrations/**
      - chloria-backend/Dockerfile.dist-migration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: metalwhaledev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:chloria-backend"
          file: Dockerfile.dist-migration
          push: true
          tags: metalwhaledev/chloria-migration:0.1.0
